"""Render a DesignerState as a runnable LangChain-style Python script."""

from __future__ import annotations

import json
from typing import Any


def _get(stages: dict, stage_id: str, key: str, default: Any) -> Any:
    return stages.get(stage_id, {}).get(key, default)


def export_python(stages: dict, *, project_name: str) -> str:
    """Emit a self-contained Python script that wires the chosen stages."""
    chunking_strategy = _get(stages, "chunking", "strategy", "recursive")
    chunk_size = int(_get(stages, "chunking", "chunk_size", 1000))
    chunk_overlap = int(_get(stages, "chunking", "chunk_overlap", 200))

    embedding_provider = _get(stages, "embedding", "provider", "openai")
    embedding_model = _get(stages, "embedding", "model", "text-embedding-3-small")

    vector_provider = _get(stages, "vector_store", "provider", "qdrant")
    vector_collection = _get(stages, "vector_store", "collection", "default")

    retrieval_strategy = _get(stages, "retrieval", "strategy", "dense")
    top_k = int(_get(stages, "retrieval", "top_k", 5))

    generator_provider = _get(stages, "generator", "provider", "openai")
    generator_model = _get(stages, "generator", "model", "gpt-4o-mini")
    generator_temperature = float(_get(stages, "generator", "temperature", 0.2))

    prompt_system = _get(
        stages,
        "prompt",
        "system",
        "You are a helpful assistant grounded in the provided context.",
    )
    prompt_user = _get(
        stages, "prompt", "user_template", "{question}\n\nContext:\n{context}"
    )

    stages_json = json.dumps(stages, indent=2, sort_keys=True)
    safe_project = project_name.replace("'", "\\'")

    return f'''"""Auto-generated RAG pipeline for project: {safe_project}

Generated by RAG-Studio. Edit freely.

Pipeline summary:
    chunking         : {chunking_strategy} (size={chunk_size}, overlap={chunk_overlap})
    embedding        : {embedding_provider} / {embedding_model}
    vector store     : {vector_provider} (collection={vector_collection})
    retrieval        : {retrieval_strategy} (top_k={top_k})
    generator        : {generator_provider} / {generator_model} (T={generator_temperature})

Configuration snapshot (full DesignerState):
{stages_json}
"""

from __future__ import annotations

import os
from typing import Any

from langchain_community.document_loaders import DirectoryLoader
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_qdrant import QdrantVectorStore
from langchain_core.prompts import ChatPromptTemplate
from langchain_text_splitters import RecursiveCharacterTextSplitter
from qdrant_client import QdrantClient


PROJECT_NAME = "{safe_project}"
COLLECTION = "{vector_collection}"
TOP_K = {top_k}


def build_vector_store() -> QdrantVectorStore:
    embeddings = OpenAIEmbeddings(model="{embedding_model}")
    client = QdrantClient(url=os.environ.get("QDRANT_URL", "http://localhost:6333"))
    return QdrantVectorStore(
        client=client,
        collection_name=COLLECTION,
        embedding=embeddings,
    )


def ingest(source_dir: str) -> None:
    """Load → split → embed → upsert."""
    loader = DirectoryLoader(source_dir)
    docs = loader.load()

    splitter = RecursiveCharacterTextSplitter(
        chunk_size={chunk_size},
        chunk_overlap={chunk_overlap},
    )
    chunks = splitter.split_documents(docs)

    store = build_vector_store()
    store.add_documents(chunks)


def answer(question: str) -> dict[str, Any]:
    store = build_vector_store()
    retriever = store.as_retriever(search_kwargs={{"k": TOP_K}})
    retrieved = retriever.invoke(question)
    context = "\\n\\n".join(d.page_content for d in retrieved)

    prompt = ChatPromptTemplate.from_messages([
        ("system", {prompt_system!r}),
        ("user", {prompt_user!r}),
    ])
    llm = ChatOpenAI(model="{generator_model}", temperature={generator_temperature})

    chain = prompt | llm
    response = chain.invoke({{"question": question, "context": context}})

    return {{
        "answer": getattr(response, "content", str(response)),
        "sources": [d.metadata for d in retrieved],
    }}


if __name__ == "__main__":
    import sys
    if len(sys.argv) < 2:
        print("Usage: python pipeline.py <question>")
        sys.exit(1)
    result = answer(" ".join(sys.argv[1:]))
    print(result["answer"])
'''
